"""removed incident added history

Revision ID: 12aa1b3dbf8e
Revises: 591b1df043d1
Create Date: 2026-08-09 20:12:22.390886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12aa1b3dbf8e'
down_revision: Union[str, Sequence[str], None] = '591b1df043d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UP', 'DOWN', name='endpointstatus'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_status_history_endpoint_id'), 'endpoint_status_history', ['endpoint_id'], unique=False)
    op.drop_index(op.f('ix_incidents_endpoint_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('endpoint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], name=op.f('incidents_endpoint_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('incidents_pkey'))
    )
    op.create_index(op.f('ix_incidents_endpoint_id'), 'incidents', ['endpoint_id'], unique=False)
    op.drop_index(op.f('ix_endpoint_status_history_endpoint_id'), table_name='endpoint_status_history')
    op.drop_table('endpoint_status_history')
    # ### end Alembic commands ###
