"""added telegram account

Revision ID: 3596b5e8f81c
Revises: 368f3128f478
Create Date: 2026-08-18 23:57:31.350623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3596b5e8f81c'
down_revision: Union[str, Sequence[str], None] = '368f3128f478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('endpoint_url', sa.String(length=2048), nullable=False))
    op.add_column('outbox_events', sa.Column('latency_ms', sa.Integer(), nullable=False))
    op.alter_column('telegram_link_tokens', 'token',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telegram_link_tokens', 'token',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_column('outbox_events', 'latency_ms')
    op.drop_column('outbox_events', 'endpoint_url')
    # ### end Alembic commands ###
