"""added claimed fncs 

Revision ID: 51aecd67f4e3
Revises: 9925191a829f
Create Date: 2026-08-13 09:47:00.041217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51aecd67f4e3'
down_revision: Union[str, Sequence[str], None] = '9925191a829f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('claimed_at', sa.DateTime(), nullable=True))
    op.add_column('outbox_events', sa.Column('claimed_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'claimed_by')
    op.drop_column('outbox_events', 'claimed_at')
    # ### end Alembic commands ###
