"""added necessary cols

Revision ID: 5feee2df96ac
Revises: 2210156c5341
Create Date: 2026-08-08 19:42:48.121482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5feee2df96ac'
down_revision: Union[str, Sequence[str], None] = '2210156c5341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('current_status', sa.String(length=20), nullable=True))
    op.add_column('endpoints', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('endpoints', sa.Column('latency', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoints', 'latency')
    op.drop_column('endpoints', 'status_code')
    op.drop_column('endpoints', 'current_status')
    # ### end Alembic commands ###
